/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConcurrencySettings: typeof import('./src/components/settings/ConcurrencySettings.vue')['default']
    DocumentViewerDialog: typeof import('./src/components/module/DocumentViewerDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GeneratePointsDialog: typeof import('./src/components/module/GeneratePointsDialog.vue')['default']
    GenerationProgressDialog: typeof import('./src/components/module/GenerationProgressDialog.vue')['default']
    MemberList: typeof import('./src/components/project/MemberList.vue')['default']
    ModuleList: typeof import('./src/components/project/ModuleList.vue')['default']
    PointsPreviewDialog: typeof import('./src/components/module/PointsPreviewDialog.vue')['default']
    ProjectOverview: typeof import('./src/components/project/ProjectOverview.vue')['default']
    ProjectSettings: typeof import('./src/components/project/ProjectSettings.vue')['default']
    ProjectTestCases: typeof import('./src/components/project/ProjectTestCases.vue')['default']
    RequirementDocs: typeof import('./src/components/module/RequirementDocs.vue')['default']
    RequirementPoints: typeof import('./src/components/module/RequirementPoints.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestCases: typeof import('./src/components/module/TestCases.vue')['default']
    TestCategories: typeof import('./src/components/settings/TestCategories.vue')['default']
    TestDesignMethods: typeof import('./src/components/settings/TestDesignMethods.vue')['default']
    TestPoints: typeof import('./src/components/module/TestPoints.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
